version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=db
    command : mix phx.server
    volumes:
      - $PWD/assets:/app/assets
      - $PWD/config:/app/config
      - $PWD/lib:/app/lib
      - $PWD/priv:/app/priv
      - $PWD/test:/app/test
      - $PWD/mix.exs:/app/mix.exs
      - ~/.aws:/root/.aws:ro
    ports:
      - "4001:4001"
    depends_on:
      - db
  db:
    image: "postgres:11"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all
    environment:
      POSTGRES_DB: "leyden_jar_dev"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: "leyden_jar_db"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  test_db:
    image: "postgres:11"
    environment:
      POSTGRES_DB: "leyden_jar_test"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: "leyden_jar_db_test"
volumes:
  data:
    driver: local
