version: "3"
services:
  web:
    container_name: leyden_jar_elixir
    build: .
    environment:
      - DB_HOST=db
      - SECRET_KEY_BASE"
    env_file:
      - .env
    command: mix phx.server
    volumes:
      - $PWD:/app
      - ~/.aws:/root/.aws:ro
    ports:
      - "127.0.0.1:4001:4001"
    depends_on:
      - db
  db:
    image: "postgres:11"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all
    environment:
      POSTGRES_DB: "leyden_jar_dev"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: "leyden_jar_postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
