use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :leyden_jar, LeydenJarWeb.Endpoint,
  url: [host: "leydenjar.app", scheme: "https", port: 443],
  http: [
    port: String.to_integer(System.get_env("HTTP_PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info
import_config "prod.secret.exs"
